import{useEffect,useMemo,useState}from'react';
import{Alert,Image,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import MapView,{Marker,PROVIDER_GOOGLE,MapPressEvent}from'react-native-maps';
import*as Location from'expo-location';
import{api,messageFrom,assetUrl}from'@/lib/api';
import type{Car}from'@/lib/types';
import{AlertBox,Button,Card,Field}from'@/components/ui/kit';
import{C,shadow}from'@/constants/app-theme';
type Point={address:string;lat:number|null;lng:number|null};
const calc=(a:Point,b:Point)=>{if(a.lat==null||a.lng==null||b.lat==null||b.lng==null)return 0;const dLat=(b.lat-a.lat)*Math.PI/180,dLng=(b.lng-a.lng)*Math.PI/180,x=Math.sin(dLat/2)**2+Math.cos(a.lat*Math.PI/180)*Math.cos(b.lat*Math.PI/180)*Math.sin(dLng/2)**2;return 6371*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))};
const img=(url?:string|null)=>assetUrl(url)||'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=900';
export default function Home(){
 const[cars,setCars]=useState<Car[]>([]),[hero,setHero]=useState(''),[selected,setSelected]=useState<number|null>(null);
 const[pickup,setPickup]=useState<Point>({address:'',lat:null,lng:null}),[drop,setDrop]=useState<Point>({address:'',lat:null,lng:null});
 const[selecting,setSelecting]=useState<'pickup'|'drop'>('pickup'),[date,setDate]=useState(''),[time,setTime]=useState(''),[loading,setLoading]=useState(false),[error,setError]=useState('');
 useEffect(()=>{Promise.all([api.get('/cars'),api.get('/settings/home')]).then(([a,b])=>{setCars(a.data);setHero(b.data.heroImageUrl||'');if(a.data[0])setSelected(a.data[0].id)}).catch(e=>setError(messageFrom(e,'Could not load fleet.')))},[]);
 const km=useMemo(()=>calc(pickup,drop),[pickup,drop]),car=cars.find(x=>x.id===selected),total=car?km*Number(car.pricePerKm):0;
 const current=async()=>{const p=await Location.requestForegroundPermissionsAsync();if(!p.granted)return Alert.alert('Location needed','Allow location access to set your pickup.');const loc=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setPickup({lat:loc.coords.latitude,lng:loc.coords.longitude,address:'Current location'});setSelecting('drop')};
 const mapTap=(e:MapPressEvent)=>{const{latitude:lat,longitude:lng}=e.nativeEvent.coordinate,p={lat,lng,address:(selecting==='pickup'?'Map pickup':'Map destination')+' ('+lat.toFixed(4)+', '+lng.toFixed(4)+')'};if(selecting==='pickup'){setPickup(p);setSelecting('drop')}else setDrop(p)};
 const book=async()=>{if(!selected||!pickup.address||!drop.address||!km||!date||!time)return setError('Choose a car, route, date and time.');try{setLoading(true);setError('');await api.post('/bookings',{carId:selected,pickupAddress:pickup.address,pickupLat:pickup.lat,pickupLng:pickup.lng,dropAddress:drop.address,dropLat:drop.lat,dropLng:drop.lng,distanceKm:Number(km.toFixed(2)),travelDate:date,travelTime:time});Alert.alert('Ride booked','Your booking is pending confirmation.')}catch(e){setError(messageFrom(e,'Could not create booking.'))}finally{setLoading(false)}};
 return <ScrollView style={s.page} contentContainerStyle={{paddingBottom:100}}>
  <View style={s.hero}>{hero?<Image source={{uri:assetUrl(hero)}} style={StyleSheet.absoluteFill}/>:null}<View style={s.overlay}/><SafeAreaView style={s.heroContent}><Text style={s.kicker}>PREMIUM RIDES</Text><Text style={s.heroTitle}>The city is yours.{"\n"}<Text style={{color:'#60a5fa'}}>Ride beautifully.</Text></Text><Text style={s.heroSub}>Upfront pricing, scheduled rides and live tracking.</Text></SafeAreaView></View>
  <View style={s.body}><Card><Text style={s.cardKicker}>PLAN YOUR JOURNEY</Text><Text style={s.heading}>Where are you going?</Text><View style={{gap:12,marginTop:18}}><Button title="Use my current pickup" variant="secondary" onPress={current}/><Field value={pickup.address} onChangeText={address=>setPickup(v=>({...v,address}))} placeholder="Pickup address"/><Field value={drop.address} onChangeText={address=>setDrop(v=>({...v,address}))} placeholder="Destination address"/><View style={{flexDirection:'row',gap:10}}><Field value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" style={{flex:1}}/><Field value={time} onChangeText={setTime} placeholder="HH:MM" style={{flex:1}}/></View></View></Card>
  <Text style={s.section}>Choose your car</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{gap:12}}>{cars.map(item=><Pressable key={item.id} onPress={()=>setSelected(item.id)} style={[s.car,selected===item.id&&s.carSelected]}><Image source={{uri:img(item.imageUrl)}} style={s.carImage}/><View style={{padding:13}}><Text style={s.carName}>{item.name}</Text><Text style={s.muted}>{item.type}</Text><Text style={s.price}>{'$'+item.pricePerKm+'/km'}</Text></View></Pressable>)}</ScrollView>
  <View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={s.section}>Set route on map</Text><Text style={s.muted}>Tap to set {selecting}.</Text></View><Button title={selecting==='pickup'?'Pickup':'Drop'} variant="secondary" onPress={()=>setSelecting(v=>v==='pickup'?'drop':'pickup')}/></View>
  <View style={s.map}><MapView provider={PROVIDER_GOOGLE} style={{flex:1}} initialRegion={{latitude:34.5553,longitude:69.2075,latitudeDelta:.12,longitudeDelta:.12}} onPress={mapTap}>{pickup.lat!=null&&pickup.lng!=null?<Marker coordinate={{latitude:pickup.lat,longitude:pickup.lng}} pinColor={C.blue}/>:null}{drop.lat!=null&&drop.lng!=null?<Marker coordinate={{latitude:drop.lat,longitude:drop.lng}} pinColor={C.red}/>:null}</MapView></View>
  <Card style={{backgroundColor:C.navy,borderColor:C.navy}}><View style={{flexDirection:'row',justifyContent:'space-between',alignItems:'center'}}><View><Text style={{color:'#94a3b8'}}>Estimated fare</Text><Text style={{color:'#fff',fontSize:32,fontWeight:'900'}}>{'$'+total.toFixed(2)}</Text></View><Text style={{color:'#94a3b8'}}>{km?km.toFixed(2)+' km':'Route pending'}</Text></View><View style={{marginTop:14,gap:10}}><AlertBox message={error}/><Button title="Confirm booking" loading={loading} onPress={book}/></View></Card></View>
 </ScrollView>
}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},hero:{height:420,backgroundColor:C.navy},overlay:{...StyleSheet.absoluteFill,backgroundColor:'rgba(2,6,23,.68)'},heroContent:{padding:24,justifyContent:'center',flex:1},kicker:{color:'#60a5fa',fontSize:12,fontWeight:'900',letterSpacing:2},heroTitle:{color:'#fff',fontSize:42,lineHeight:47,fontWeight:'900',letterSpacing:-1.5,marginTop:15},heroSub:{color:'#cbd5e1',fontSize:16,lineHeight:24,marginTop:16},body:{padding:16,marginTop:-34,gap:18},cardKicker:{color:C.blue,fontSize:11,fontWeight:'900',letterSpacing:1.5},heading:{fontSize:26,fontWeight:'900',color:C.text,marginTop:6},section:{fontSize:21,fontWeight:'900',color:C.text,marginTop:6},car:{width:210,borderRadius:20,overflow:'hidden',backgroundColor:'#fff',borderWidth:2,borderColor:'transparent',...shadow},carSelected:{borderColor:C.blue},carImage:{width:'100%',height:115,backgroundColor:'#e2e8f0'},carName:{fontSize:16,fontWeight:'900',color:C.text},muted:{color:C.muted,fontSize:13,marginTop:3},price:{color:C.blue,fontWeight:'900',marginTop:7},map:{height:260,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:C.line}})
