import{useCallback,useEffect,useRef,useState}from'react';
import{Alert,Image,Pressable,RefreshControl,ScrollView,StyleSheet,Text,View}from'react-native';
import{SafeAreaView}from'react-native-safe-area-context';
import*as Location from'expo-location';import*as ImagePicker from'expo-image-picker';
import{useAuth}from'@/context/auth';import{api,messageFrom,assetUrl}from'@/lib/api';import{getSocket}from'@/lib/socket';
import type{Booking,Car}from'@/lib/types';import{AlertBox,Button,Card,Field}from'@/components/ui/kit';import{C}from'@/constants/app-theme';
export default function Role(){const{user}=useAuth();if(user?.role==='driver')return <Driver/>;if(user?.role==='admin')return <Admin/>;return <Explore/>}
function Explore(){return <SafeAreaView style={s.page}><ScrollView contentContainerStyle={s.body}><Text style={s.kicker}>WHY CARBOOKING</Text><Text style={s.title}>Move with confidence</Text><Text style={s.sub}>Everything you need for a predictable, trackable ride.</Text>{[['Upfront pricing','Distance and fare update before you confirm.'],['Live tracking','Follow your assigned driver in real time.'],['Protected payments','Stripe handles card details securely.'],['Flexible history','Search past and upcoming journeys.']].map(([a,b])=><Card key={a}><Text style={s.heading}>{a}</Text><Text style={s.sub}>{b}</Text></Card>)}</ScrollView></SafeAreaView>}
function Driver(){const[rides,setRides]=useState<Booking[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[sharing,setSharing]=useState<number|null>(null);const watch=useRef<Location.LocationSubscription|null>(null);
 const load=useCallback(async()=>{try{setLoading(true);setRides((await api.get('/tracking/driver/rides')).data);setError('')}catch(e){setError(messageFrom(e))}finally{setLoading(false)}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load();return()=>watch.current?.remove()},[load]);
 const claim=async(id:number)=>{try{await api.post('/tracking/'+id+'/claim');load()}catch(e){Alert.alert('Could not claim',messageFrom(e))}};
 const share=async(id:number)=>{const p=await Location.requestForegroundPermissionsAsync();if(!p.granted)return Alert.alert('Location required','Allow foreground location to share with the rider.');await claim(id);const socket=await getSocket();socket.emit('join-booking',id);watch.current?.remove();watch.current=await Location.watchPositionAsync({accuracy:Location.Accuracy.High,timeInterval:3000,distanceInterval:5},loc=>socket.emit('driver-location',{bookingId:id,latitude:loc.coords.latitude,longitude:loc.coords.longitude,accuracy:loc.coords.accuracy,heading:loc.coords.heading,speed:loc.coords.speed}));setSharing(id)};
 const stop=async(id:number)=>{watch.current?.remove();watch.current=null;(await getSocket()).emit('stop-sharing',id);await api.put('/tracking/'+id+'/stop');setSharing(null)};
 return <SafeAreaView style={s.page}><View style={s.darkHead}><Text style={s.kicker}>DRIVER CONSOLE</Text><Text style={s.darkTitle}>Ready rides</Text><Text style={s.darkSub}>Claim an accepted ride and share live location.</Text></View><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={[s.body,{marginTop:-24}]}><AlertBox message={error}/>{rides.map(r=><Card key={r.id}><View style={s.between}><View><Text style={s.heading}>Booking #{r.id}</Text><Text style={s.sub}>{r.Car?.name} · {r.travelDate} {String(r.travelTime).slice(0,5)}</Text></View><Text style={s.fare}>{'$'+Number(r.totalPrice).toFixed(2)}</Text></View><Text style={s.route}>● {r.pickupAddress}{"\n"}{"\n"}<Text style={{color:C.red}}>● {r.dropAddress}</Text></Text><View style={{gap:8,marginTop:16}}>{sharing===r.id?<Button title="Stop sharing location" variant="danger" onPress={()=>stop(r.id)}/>:<Button title={r.RideTracking?'Start sharing location':'Claim and start ride'} onPress={()=>share(r.id)}/>}</View></Card>)}{!rides.length?<Text style={s.empty}>No accepted rides are available.</Text>:null}</ScrollView></SafeAreaView>}
function Admin(){const[bookings,setBookings]=useState<Booking[]>([]),[cars,setCars]=useState<Car[]>([]),[section,setSection]=useState<'bookings'|'fleet'>('bookings'),[loading,setLoading]=useState(false),[error,setError]=useState('');const[name,setName]=useState(''),[type,setType]=useState(''),[price,setPrice]=useState(''),[imageUrl,setImageUrl]=useState('');
 const load=useCallback(async()=>{try{setLoading(true);const[b,c]=await Promise.all([api.get('/bookings/all',{params:{limit:50}}),api.get('/cars')]);setBookings(b.data.bookings);setCars(c.data);setError('')}catch(e){setError(messageFrom(e))}finally{setLoading(false)}},[]);
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{load()},[load]);
 const status=async(id:number,value:string)=>{try{await api.put('/bookings/'+id+'/status',{status:value});load()}catch(e){Alert.alert('Update failed',messageFrom(e))}};
 const pick=async(target:'car'|'hero')=>{const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted)return Alert.alert('Photos needed','Allow photo access to upload an image.');const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],allowsEditing:true,quality:.8});if(result.canceled)return;const asset=result.assets[0],form=new FormData();form.append('image',{uri:asset.uri,name:asset.fileName||target+'-'+Date.now()+'.jpg',type:asset.mimeType||'image/jpeg'} as any);try{const{data}=await api.post('/uploads/image',form,{headers:{'Content-Type':'multipart/form-data'}});if(target==='car')setImageUrl(data.imageUrl);else{await api.put('/settings/home',{heroImageUrl:data.imageUrl});Alert.alert('Published','Homepage hero updated.')}}catch(e){setError(messageFrom(e,'Could not upload image.'))}};
 const add=async()=>{if(!name||!type||!price)return setError('Complete the car name, type and price.');try{await api.post('/cars',{name,type,pricePerKm:Number(price),imageUrl:imageUrl||null});setName('');setType('');setPrice('');setImageUrl('');load()}catch(e){setError(messageFrom(e,'Could not add car.'))}};
 return <SafeAreaView style={s.page}><View style={s.darkHead}><Text style={s.kicker}>ADMIN CONTROL</Text><Text style={s.darkTitle}>Operations</Text><View style={s.tabs}><Pressable onPress={()=>setSection('bookings')} style={[s.tab,section==='bookings'&&s.tabOn]}><Text style={section==='bookings'?s.tabTextOn:s.tabText}>Bookings</Text></Pressable><Pressable onPress={()=>setSection('fleet')} style={[s.tab,section==='fleet'&&s.tabOn]}><Text style={section==='fleet'?s.tabTextOn:s.tabText}>Fleet</Text></Pressable></View></View><ScrollView refreshControl={<RefreshControl refreshing={loading} onRefresh={load}/>} contentContainerStyle={[s.body,{marginTop:-20}]}><AlertBox message={error}/>{section==='bookings'?bookings.map(b=><Card key={b.id}><View style={s.between}><View><Text style={s.heading}>Booking #{b.id}</Text><Text style={s.sub}>{b.User?.name} · {b.Car?.name}</Text></View><Text style={s.fare}>{'$'+Number(b.totalPrice).toFixed(2)}</Text></View><Text style={s.route}>● {b.pickupAddress}{"\n"}{"\n"}<Text style={{color:C.red}}>● {b.dropAddress}</Text></Text><Text style={{marginTop:12,fontWeight:'900',color:C.blue}}>{b.status.toUpperCase()} · {b.paymentStatus.toUpperCase()}</Text><View style={{flexDirection:'row',gap:7,marginTop:14}}>{['accepted','completed','cancelled'].map(v=><Pressable key={v} onPress={()=>status(b.id,v)} style={[s.smallAction,v==='cancelled'&&{backgroundColor:C.redSoft}]}><Text style={{fontWeight:'800',fontSize:11,color:v==='cancelled'?C.red:C.blue}}>{v}</Text></Pressable>)}</View></Card>):<><Card><Text style={s.heading}>Add a vehicle</Text><View style={{gap:11,marginTop:15}}><Field value={name} onChangeText={setName} placeholder="Car name"/><Field value={type} onChangeText={setType} placeholder="Vehicle type"/><Field value={price} onChangeText={setPrice} keyboardType="decimal-pad" placeholder="Price per km"/><Field value={imageUrl} onChangeText={setImageUrl} placeholder="Image URL or upload below"/><Button title="Choose car image" variant="secondary" onPress={()=>pick('car')}/><Button title="Add to fleet" onPress={add}/><Button title="Upload and publish hero" variant="secondary" onPress={()=>pick('hero')}/></View></Card>{cars.map(c=><Card key={c.id}><View style={{flexDirection:'row',gap:12,alignItems:'center'}}>{c.imageUrl?<Image source={{uri:assetUrl(c.imageUrl)}} style={{width:82,height:58,borderRadius:12}}/>:null}<View><Text style={s.heading}>{c.name}</Text><Text style={s.sub}>{c.type} · {'$'+c.pricePerKm+'/km'}</Text></View></View></Card>)}</>}</ScrollView></SafeAreaView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:C.bg},body:{padding:16,gap:13,paddingBottom:100},kicker:{color:'#60a5fa',fontWeight:'900',fontSize:11,letterSpacing:1.6},title:{fontSize:36,fontWeight:'900',color:C.text,marginTop:8},sub:{color:C.muted,lineHeight:21,marginTop:5},heading:{fontSize:18,fontWeight:'900',color:C.text},darkHead:{backgroundColor:C.navy,padding:22,paddingBottom:48},darkTitle:{color:'#fff',fontSize:34,fontWeight:'900',marginTop:8},darkSub:{color:'#94a3b8',marginTop:8},between:{flexDirection:'row',justifyContent:'space-between',gap:10},fare:{fontWeight:'900',fontSize:18},route:{lineHeight:20,marginTop:17,color:C.blue},empty:{textAlign:'center',color:C.muted,padding:40},tabs:{flexDirection:'row',backgroundColor:'rgba(255,255,255,.08)',padding:4,borderRadius:14,marginTop:20},tab:{flex:1,padding:11,alignItems:'center',borderRadius:11},tabOn:{backgroundColor:'#fff'},tabText:{color:'#94a3b8',fontWeight:'800'},tabTextOn:{color:C.navy,fontWeight:'900'},smallAction:{flex:1,backgroundColor:C.blueSoft,padding:10,borderRadius:10,alignItems:'center'}})
