const User = require("./User");
const Car = require("./Car");
const Booking = require("./Booking");
const RideTracking = require("./RideTracking");
const Notification = require("./Notification");
const SiteSetting = require("./SiteSetting");
const PasswordResetToken = require("./PasswordResetToken");
User.hasMany(Booking);
Booking.belongsTo(User);
Car.hasMany(Booking);
Booking.belongsTo(Car);
Booking.hasOne(RideTracking, { onDelete: "CASCADE" });
RideTracking.belongsTo(Booking);
User.hasMany(RideTracking, { foreignKey: "DriverId", as: "DriverTrackings" });
RideTracking.belongsTo(User, { foreignKey: "DriverId", as: "Driver", onDelete: "RESTRICT" });
User.hasMany(Notification, { onDelete: "CASCADE" });
Notification.belongsTo(User);
User.hasMany(PasswordResetToken, { onDelete: "CASCADE" });
PasswordResetToken.belongsTo(User);
module.exports = { User, Car, Booking, RideTracking, Notification, SiteSetting, PasswordResetToken };